
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/tams?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 30000
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.lhd.tams: debug
